app/views/shared/representativeForm.hbs
This is a tiny fix, so I figured I'd just take care of it.  ✅  I think the rep's title broke in the last refactor.  I changed the `camelCase` back to `lower_case_snake_case` for the key names here.  🔑   I don't care which style we go with in the long-term (as long as we stick entirely with one or the other), but this should fix it for now.  🐫 🐍 👍
=> [FINAL] Fixing the Representative's title

app/views/campaignSuccess.hbs
Make "preview url" & "go to campaigns" link clickable in areas within the button but outside of the text
=> Fix buttons on Campaign Success page

.editorconfig, .gitignore, app/middleware/campaign.js, app/middleware/event.js, app/routes/analytics.js, app/routes/api/campaign.js, app/routes/api/event.js, app/routes/api/index.js, app/routes/campaign.js, app/routes/index.js, public/js/core.js
Note: This PR is additive from the previous PR. Once that one is merged one of the commits will not show up in this diff. 
For this PR I pulled out the ajax routes into a separate /api routing, because when I did the first ticket it was super confusing to me that the full page routes were intermixed with what was essentially a JSON API. This will also allow us in the future to do specific things with these routes only, like require an API key, or a different caching scheme, or some other various middleware specific to an API that is expected to be used client side. I also made the routes RESTful, which I think is a lot easier to work with client side (and a best practice to follow).
I also started making a change to the way we're interacting with mongoose, but then thought better of going …
=> Pull API routes out from main routes and make them RESTful.

app/views/layouts/main.hbs
The address autocomplete doesn't work on staging (and any SSL environment) without the Google Maps JS being loaded over SSL as well (at least in Chrome, and probably other browsers too).
=> Switch Google Maps script to HTTPS.

.gitignore, app/routes/index.js, conf/config.js
Note that until we re-enable the faq and request-beta-access pages on squarespace, we're proxying squarespace 404s.
=> allow proxy to a list of marketing site urls

README.md
Adds instructions for how to run the mongo shell in docker to the README.
I had to google how to do this last night so I figured I'd save myself and everyone else the trouble in the future 😖
=> add instructions for running the mongo shell

app/controllers/campaign.js, app/views/campaign.hbs, public/js/campaign/visitor.controller.js, public/js/create/createPage.component.js, public/js/create/createPage.html
Added feature to respond with meaningful messages when the user enters an invalid state:
- If the user enters an invalid state for a state-level campaign, they will be notified that their state isn't relevant to the campaign.
- If the user enters a state outside of the US 50 & PR for any campaign, they will be prompted to do so.
Also added Puerto Rico to the state selection.
=> Add State Error Handling

public/js/create/createPage.html
Set explicit tab indexes for campaign fields. Order is as follows:
1. Campaign title
2. Federal: Senate (if enabled)
3. Federal: House (if enabled)
4. State: Senate (if enabled)
5. State: Assembly (if enabled)
6. State select dropdown (if visible)
7. Script
8. Thank you message
9. Learn more URL
10. Save as draft
11. Submit
12. Cancel
Tab-selecting the state dropdown will bring it into focus (but not expand it). To expand it, you can either click it or hit the spacebar. While the dropdown is focused, you can also begin typing your state name to select it.
By default, Safari will ignore the legislative checkbox tab indexes unless some settings are changed in Preferences -> Advanced -> Press tab to highlight each item on a page
=> tab indexes for create/edit campaign fields (issue #227)

public/scss/main.scss
resolves #220 
|   | before | after|
|---|---|---|
| mobile | <img width="410" alt="Screen Shot 2019-06-03 at 7 45 51 PM" src="https://user-images.githubusercontent.com/17886804/58847643-9a81d000-8638-11e9-97d7-a2270283285f.png"> | <img width="412" alt="Screen Shot 2019-06-03 at 7 46 13 PM" src="https://user-images.githubusercontent.com/17886804/58847648-9e155700-8638-11e9-820c-6b3c06c561c8.png">  |
| desktop | <img width="1420" alt="Screen Shot 2019-06-03 at 7 45 43 PM" src="https://user-images.githubusercontent.com/17886804/58847639-96ee4900-8638-11e9-894a-d85b0bc3a4e2.png">  | <img width="1424" alt="Screen Shot 2019-06-03 at 7 46 05 PM" src="https://user-images.githubusercontent.com/17886804/58847647-9c4b9380-8638-11e9-9165-1194add68e54.png">  |
=> fix .section-header css

public/js/campaign/visitor.controller.js
Switched up the way we pull the campaign ID from the URL on a campaign page. In the tests I did, search params in the URL no longer break address search form submission.
If this new method works, we can also apply it to a few other files that have FIXME comments related to campaign IDs in the URL.
=> [#244] query strings no longer break address searches

public/js/create/createPage.html
Fixes: #258 
Changes campaign creation fields from  'Max 800 characters' to dynamic '70/800'.
Additionally, the Learn More URL `<textarea>` is checked for validity.
While working on this, I noticed the description at the top of the create page says the following:
> Optionally, you can add a link for them to learn more about the topic. 
However, the Submit validation expects a Learn More URL. I may need to open another issue to address this.
=> [#258] Add field length feedback to campaign form

app/views/layouts/main.hbs
The content-wrapper div that wraps the bulk of the app's content had an onclick event attached to it which fired the function closeNav(). closeNav() closes the sidebar when a user clicks anywhere on that div, but it was failing because there is only a sidebar for logged in users.
=> [#250] fix console errors on click for non-logged in users

public/js/account/resetPassword.component.js, public/js/account/signupPage.component.js, public/js/analytics/analyticsPage.component.js, public/js/campaign/thanksPage.component.js, public/js/create/createPage.component.js, public/js/create/createSuccessPage.component.js
I implemented the URL parsing method from #249 in a few other places in our code where there are FIXMEs referencing brittle URL parsing. 
There will be some instances where the final .replace(/[/]/g, '') call (which strips out any '/' characters) will be unnecessary. This is done to make doubly sure that if a trailing slash does get added to the URL for whatever reason, it won't affect the app's ability to parse out what it needs.
=> New URL parsing method

app/views/campaign.hbs, public/js/home/campaigns-list.component.js, public/js/home/campaigns-list.html, public/scss/campaigns.scss
resolves #151 
As an admin I want data about how many people have viewed/called my campaign so that I know how effective it has been. Originally we thought we would make this its own analytics page, but for the time being with only two figures it seemed appropriate to add it to the campaign list.
@jschnapper made a good start on this issue in his PR #203. Unfortunately since he hasn't been in contact with us recently his PR had to be closed, but I have picked up where he left off!
| | before | after |
|---|---|---|
| **mobile** | <img width="340" alt="Screen Shot 2019-06-11 at 7 27 23 AM" src="https://user-images.githubusercontent.com/17886804/59280404-63a05100-8c1a-11e9-96ca-0f542b619d34.png"> | ![Untitled4](https://user-images.githubusercontent.com/17886804/60064263-b23afa00-96b4-11e9-82 …
=> [#151] Add basic analytics to Campaign list page

public/js/create/createPage.html
Fixes #266
Provides users with error message for the specific field when creating a campaign if the contents are invalid or incomplete.
Only appears after the user has interacted with the text area.
=> [#266] Campaign Creation Form Feedback

app/views/campaign.hbs, public/js/campaign/visitor.controller.js
Set some config options so that the autocomplete form will (mostly) return complete addresses. Searching for a zip code or city should now return either nothing in the list, or a list of businesses with full addresses that start with those strings. EX: 90210 Car Rental, California Donuts, California Science Center, etc.
There are some weird edge cases where it still returns just a city, state, and zip code (like searching 'Burbank Airport'): 
In those cases we now have an error message:
=> [#211] Error message for incomplete addresses + partial address filtering

public/scss/buttons.scss
Addresses #236
Fixes wrapping of text inside button when viewing the *Home* page (and other buttons) on mobile.
Before
After
- Change button padding to use a percentage. This resolves mobile responsive designs as the measurement is taken with respect to the size of the screen, rather than the absolute unit.
=> [#236] Relative padding for mobile buttons

app/routes/user.js
resolves #278 
Users shouldn't be allowed to log in again or access the 'forgot password' page if they are already logged in.
There are now server-side checks for logged in users upon navigating to <code>/login</code> and <code>/auth/forgot-password</code>. If a user is logged in, they will be redirected to <code>/home</code> in both cases.
=> [#278] added checks and redirects on auth pages for logged in users

public/js/campaign/visitor.controller.js
Resolves #287 
> Autofill is not working on all addresses, whoever has time to look at this bug
> 
> ex: https://www.hellogov.app/O34QJGN5I
Before
After
* Remove validation for public establishments in Google places Autocomplete request:
https://developers.google.com/places/web-service/autocomplete
=> [#287] Google Places Autocomplete Filter

public/js/home/campaigns-list.html, public/scss/campaigns.scss
resolves #282
my previous PR #259 introduced an overflow bug in mobile when the titles are long
My flexbox magic was unnecessarily complicated, so I made it simpler and allowed the title to grow without overflowing over the next elements.
| | before | after |
|--|---|---|
| mobile | <img width="375" alt="Screen Shot 2019-07-31 at 11 07 36 AM" src="https://user-images.githubusercontent.com/17886804/62236214-749c5180-b383-11e9-9b09-2991d2740aef.png"> | ![untitled1](https://user-images.githubusercontent.com/17886804/62236025-12435100-b383-11e9-9a72-be269ab67d15.gif) |
| desktop | <img width="845" alt="Screen Shot 2019-07-31 at 11 07 47 AM" src="https://user-images.githubusercontent.com/17886804/62236221-7c5bf600-b383-11e9-9aed-3e7733a7ba8b.png"> | <img width="1221" alt="Screen Shot …
=> [#282] campaign title covers buttons in mobile view

package.json
for some reason heroku needed the node version specified all of a sudden? ok
- added the node version in package.json
=> add node version to package.json

app/models/signup.js
resolves #323 
Email was case sensitive and the error was confusing if the user used a different capitalization as the admin had entered for their email. 
Pretty much what it says in the title. Signups w/ capital letters that are pending when this gets merged in will be left in stuck state. If there are signups in this state, we'd have to delete/fix those in the DB directly since there's isn't an API.
Inspired by: https://stackoverflow.com/a/13991704
=> [#323] Make the email field have a lowercase type to make it case insensitive
