helloGov/webapp

legislators-locate.js, public/ie10-viewport-bug-workaround.css, public/mapAPI.js, views/home.hbs, views/layouts/main.hbs, views/partials/representativeForm.hbs, views/partials/representativeNotFoundMessage.hbs
Hoping I didn't break anything.  🔨
=> Aaron's "representative not found" message and some tweaks.

app/routes/campaign.js, app/views/campaign.hbs
Tiny CR. There was no URL routing before to the campaign page we prototyped at the first hackathon. Fixed that.
=> allowing access to the original campaign page

app/middleware/influencer.js, app/routes/influencer.js, app/routes/user.js
Not sure what the standard is here, but I'm passing both request and response to the function, and just passing the function itself into the post route. I'm not sure how we can avoid passing both here since to register a user, we need to pass the entire request and response objects.
=> Move signup from routing to middleware

app/models/campaign.js, app/routes/userViews.js, app/views/create.hbs, app/views/login.hbs, package.json, public/js/core.js
Fix create campaign page to save to Mongo, and put in 'save as draft' functionality to save with publish flag 'false'. Also saving campaigns with shortid
=> Campaign page fix, save as draft functionality, add shortid

app/routes/campaign.js, app/views/campaignSuccess.hbs, package.json, public/css/campaignSuccess.css
Begins to address Issue #32 with a static page. Need to incorporate dynamic content when functionality is ready. Also swap out yellow link icon for blue link button when asset is available.
=> Campaign Creation Success page

app/middleware/campaign.js, app/routes/campaign.js, app/views/campaignSuccess.hbs, public/js/core.js
=> Campaign success

app/views/layouts/main.hbs, public/css/main.css
The logo is centered and the icons on the top nav bar are now much better aligned... may not be perfect but should be pretty close.
I also made it so the logo on the top menu bar links to the home page. This wasn't in the mockup but seems like a good idea for easier navigation.
=> Center logo

app/routes/campaign.js, app/routes/index.js, app/views/404.hbs, public/css/404.css
Still need to figure out how to get it to actually display
=> Create very basic 404 page

app/routes/campaign.js
Thank-you page now renders after user clicks "I'm done"
=> Fix route to thank-you page

app/routes/index.js, app/views/campaign.hbs, app/views/campaignDemo.hbs, app/views/profile.hbs, public/css/login.css, public/js/core.js
- Create Profile edit page
- Remove footer w line & copyright from Campaign page
- Remove footer w line & copyright from Campaign Demo page
=> Profile page & remove footer

app/middleware/campaign.js, app/middleware/event.js, app/middleware/influencer.js, app/middleware/signup.js, app/models/index.js, app/models/influencer.js, app/models/signup.js, app/routes/api/admin.js, app/routes/api/index.js, app/routes/index.js, app/routes/influencer.js, app/views/admin.hbs, app/views/error.hbs, app/views/login.hbs, app/views/signup.hbs, public/js/core.js
Design:
1. We create a new doc with an email and signupLink in mongo under the "signups" collection. This is currently a manual process (meaning you have to go into mongo and add this entry), though I plan to add an admin page to make this process simple.
2. We provide any new influencers with the following signup link: /signup/:signupLink
3. If the influencer's email matches with their signup link in the mongo collection, we create a new influencer entry for them. Otherwise we do not sign them up.
There's still some work to be done here - redirecting to error pages, etc. Will try to address with a coupla followup checkins.
=> Signup page

app/views/campaign.hbs, app/views/layouts/main.hbs, public/scss/buttons.scss, public/scss/campaign.scss, public/scss/main.scss
Set the following global fonts:
- font-family: 'Monteserrat', sans-serif
- "section-header" and "body-copy" classes to apply to text
- updated font size for CTA buttons
Styled Congressperson Results page for mobile (could use styling for desktop and tablet)
Cleaned up the whitespace on campaign.hbs a bit
=> Congress pg

app/views/emails/passwordResetEmail.hbs
To fix https://app.asana.com/0/280864181857972/341251758356525 and https://app.asana.com/0/280864181857972/341251758356529
=> Change text in the password reset email.

app/models/passwordReset.js, app/routes/api/auth.js
For https://app.asana.com/0/280864181857972/345176726306746
=> Upsert password reset instead of always creating a new one.

app/controllers/event.js
@WCRest this fixes that issue you mentioned in my other PR.
=> Get campaignId properly from events API call.

.gitignore
WebStorm is a cool IDE, I swear.
=> Add .idea to gitignore (WebStorm)

.gitignore, conf/config.js, package-lock.json, package.json
instead of making the developer create an env.js file just to set the environment, we can set it in the process.env :)
PS: This is a teeny tiny PR made out of VIENNA!! I'm sitting in the [Metalab](https://github.com/Metalab), it's super cool in here! So sad we don't have one in LA :'c
=> use NODE_ENV instead of requiring env.js

app/controllers/campaign.js, app/routes/index.js, app/views/campaign.hbs, app/views/layouts/main.hbs, conf/config.js, conf/env.js, index.js, package.json, public/js/campaign/visitor.controller.js, public/js/home/campaigns-list.component.js
Added API keys to secrets.js to keep them hidden in views.
Added Axios dependency for hitting APIs and switched from Sunlight to Openstates for representative results.
Note: Commit with SHA-1 40b9a33 reflects a google maps API key from the old repo. This API key is not in use.
=> Refactor to hit Openstates API for state senators and hide API keys in secrets.js

.gitignore, README.md, docker-compose.yml, index.js, package-lock.json
* Added docker-compose
* Updated README to reflect changes 
* Local development now unauthenticated at DB level
=> Dockerizing HelloGov MongoDB 

.gitignore, Procfile, app.json, app/controllers/campaign.js, app/models/passwordReset.js, app/routes/index.js, conf/config.js, index.js, package-lock.json, package.json
This PR adds the dotenv library and a heroku config file so that we can run this application on Heroku.
The secrets file has been removed entirely as a dependency as well in favor of environment variables. Any configuration related reads have to changed to camel case as well throughout the application.
=> Update heroku config

index.js
This PR removes a duplicate option in our production database URI.
=> Remove duplicate ssl option from db URI.

app.json
We can specify which environment variables are required in our heroku applications. By specifying them below, any review apps created will inherit those env variables from their parent applications.
=> Update app.json to require env inheritance.

app.json
=> Remove typo from env var.

public/js/create/createPage.html
resolves: https://github.com/helloGov/webapp/issues/179
=> changed cancel url

public/js/create/createPage.html, public/js/create/createSuccessPage.html
=> Helper text create campagin

app/controllers/campaign.js, app/models/campaign.js, app/routes/api/auth.js, app/routes/api/campaign.js, app/routes/index.js, app/views/campaign.hbs, conf/envs/development.js, index.js, package-lock.json, public/js/campaign/visitor.controller.js, public/js/create/createPage.component.js, public/js/create/createPage.html, public/js/create/createSuccessPage.html, public/js/home/campaigns-list.component.js, public/scss/create.scss
I believe I pushed an old version of master, thus removing some recent changes. This should fix the issue.
=> Re add state error handling

app/controllers/campaign.js, conf/envs/development.js
This PR updates the various files that depended on the now deleted secrets file.
=> Remove references to old configuration file.

index.js
Removes db name from the index file.
=> Update db config in app file

app/views/campaign.hbs, app/views/layouts/main.hbs, public/scss/buttons.scss
Display selected address in search input field.
Change styling on submit button to make it appear active on hover.
=> Debug address autofill

app/views/campaign.hbs
=> [#173] Add Campaign Title to Follower UI landing page

public/js/create/createPage.html, public/scss/main.scss
No particular issue, I addressed some usability issues I saw while working (e.g., campaign Title needs to be worded as a CTA intended for followers, as it's the first thing Followers see).
=> Add helper text to Create Campaign screen

public/js/home/campaigns-list.component.js, public/js/home/campaigns-list.html, public/scss/buttons.scss
UX is not a modal/pop-up - instead the buttons appear within the campaign UI.
**Test after merging:** 
- Delete button should be red with white font. 
- Cancel button should (depending on my UI accessibility PR) be white bg with blue font and border. (Without that PR it's still yellow with blue.)
=> Issue #190 - confirm before deleting campaign

public/scss/buttons.scss
Fixes certain white button text also being rendered as white on Safari.
=> fix: "I'm Done" button missing copy #235

public/js/404.html
=> fix white 404 text on white background

.github/issue_template.md, .github/pull_request_template.md
"I'm gonna steal your PR formatting" -@patchneranartkomol 
"I should just add a PR template" -me
=> add PR and issue templates

app/views/campaign.hbs
Link opens the webpage that was configured as the "learn more link" by the campaign creator. 
Opens in a new window.
=> Added "Learn more" link to Campaign landing page

public/js/home/campaigns-list.component.js, public/js/home/campaigns-list.html, public/scss/campaigns.scss
resolves #209 
It's a bad user experience to get no feedback when you click on the link button.
When a user clicks on the link button they should see text pop up letting them know it has been copied to their clipboard.
- fix css bug introduced in #259 by adding `.campaign-list` container class
- add clipboard animation css class
- add `showClipboardText` state to campaign-list controller to keep track of which clip board text is displaying
- add `toggleClipboardText` method to the campaign-list controller to toggle `showClipboardText` state
=> [#209] clipboard popup text

app/routes/api/signup.js, public/js/admin/admin.component.js, public/js/admin/admin.html, public/scss/admin.scss
Resolves #257 
Admin users cannot view all users who have completed their signup.
New **Completed signups** section
* Add a new backend API endpoint, `api/signsups/completed` that returns the `users` collection
* Display the results in the admin view
=> [#257] Completed signups admin view

app/views/layouts/main.hbs
Modifies the description and title for our social previews.
=> Change Title and Description Previews

app/models/user.js, app/routes/api/user.js, package-lock.json, public/js/account/signupPage.html
Resolves #215 
Adds an Organization name field to the signup form.
**After**
- Added `organizationName` as an optional field in the user model.
- Sign up form will require all new user signups to provide this information before submitting it.
Future tickets and PR's will inform what we do with this metadata, i.e. to show this on campaigns etc.
=> #215 Add organization name to signup field

README.md
resolves #
addresses #
| before | after |
|---|---|
|  |  |
-
=> slightly tweaked readme

public/js/create/createSuccessPage.html
… page
resolves #309
addresses #309
The url didn't fit on mobile screens.
| before | after |
|---|---|
|  |  |
- I added word break to the h3 containing the custom url in the createSuccessPage.html
=> added word break break-all to make the url wrap in the createSuccessPage.html
